# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 7
# Label requiring a response
responseRequiredLabel: czekamy_na_dane
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  Automatycznie zamknęliśmy wątek, ponieważ nie otrzymaliśmy niezbędnych danych. 
  Jeśli problem nadal występuje, to wznów wątek i  prześlij do nas informacje, o które prosiliśmy.
