# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - news
# Label to use when marking an issue as stale
staleLabel: brak_odpowiedzi
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  W tym wątku nie pojawiła się żadna nowa odpowiedź w ciągu 30 dni. Dlatego automatycznie oznaczamy go jako przeterminowany. 
  Jeśli w ciągu 7 dni nie pojawi się żadna odpowiedź, zamkniemy ten wątek.
  Dziękujemy za zaangażowanie w dyskusję.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
